### ISSUE TITLE
Failed to start Switch Root

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [random-archer/mkinitcpio-systemd-tool#10]
1. `systemd 237` changed mount behavior
* now it will `unmount` the `sysroot.mount` before `initrd-switch-root.target`

2. this produces boot error in `journalctl -e`:
```
Feb 27 10:22:32 work3 systemd[1]: Starting Switch Root...
Feb 27 10:22:32 work3 systemctl[974]: Failed to switch root: Specified switch root path '/sysroot' does not seem to be an OS tree. os-release file is missing.
Feb 27 10:22:32 work3 systemd[1]: initrd-switch-root.service: Main process exited, code=exited, status=1/FAILURE
Feb 27 10:22:32 work3 systemd[1]: initrd-switch-root.service: Failed with result 'exit-code'.
Feb 27 10:22:32 work3 systemd[1]: Failed to start Switch Root.
```
3. the immediate work around is:
* provide `secret>` as usual
* observe boot error message
* switch to debug console: `CTRL+ALT+F8`
* provide manual mount via: `mount /dev/mapper/root /sysroot`
* continue boot process via: `systemctl start initrd-switch-root.service`

**Comment by MartinX3** [comment]
I fixed this issue on my btrfs root with a subvolume rootfs by using `btrfs subvolume set-default /`.
Somehow the initframfs fstab ignores the `subvol=rootfs` or `subvolid=264` mount option.
Maybe a newer systemD update broke it?

Maybe because I switched from bios boot to uefi boot with efi- and xbootldr partition.
But that doesn't make any sense for me.
